# Generated by Django 2.0.4 on 2018-04-22 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roc_auc_score', models.FloatField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resulter.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='SVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamma', models.FloatField()),
                ('c', models.FloatField()),
                ('coef0', models.FloatField()),
                ('kernel', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='algorithm',
            name='svm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resulter.SVM'),
        ),
    ]
