# Generated by Django 2.0.4 on 2018-04-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resulter', '0002_auto_20180422_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='data_type',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='stock',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
